# Generated by Django 5.1.4 on 2025-01-16 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.TextField()),
                ('function_annotation', models.TextField(blank=True, null=True)),
                ('gene_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhylogeneticTrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_data', models.TextField()),
                ('species_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('taxonomy', models.CharField(blank=True, max_length=255, null=True)),
                ('genome_data_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionAnnotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_type', models.CharField(max_length=255)),
                ('annotation_details', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genes')),
            ],
        ),
        migrations.CreateModel(
            name='Markergenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_type', models.CharField(max_length=255)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genes')),
            ],
        ),
        migrations.AddField(
            model_name='genes',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.species'),
        ),
    ]
